jasman_database = {
    "The Shawshank Redemption": {"genres": ["drama"], "duration": 142, "IMDB_rating": 9},
    "The Godfather": {"genres": ["crime", "drama"], "duration": 175, "IMDB_rating": 9},
    "The Dark Knight": {"genres": ["action", "crime", "drama"], "duration": 152, "IMDB_rating": 8},
    "Pulp Fiction": {"genres": ["crime", "drama"], "duration": 154, "IMDB_rating": 9},
    "Forrest Gump": {"genres": ["drama", "romance"], "duration": 142, "IMDB_rating": 8},
    "Inception": {"genres": ["action", "adventure", "sci-fi"], "duration": 148, "IMDB_rating": 8},
    "The Matrix": {"genres": ["action", "sci-fi"], "duration": 136, "IMDB_rating": 7},
    "Schindler's List": {"genres": ["biography", "drama", "history"], "duration": 195, "IMDB_rating": 10},
    "The Lord of the Rings: The Return of the King": {"genres": ["action", "adventure", "drama", "fantasy"], "duration": 201, "IMDB_rating": 9},
    "Fight Club": {"genres": ["drama"], "duration": 139, "IMDB_rating": 8},
    "Scam 1990": {"genres": ["drama"], "duration": 270, "IMDB_rating": 9},
    "The Conjuring": {"genres": ["horror"], "duration": 112, "IMDB_rating": 7},
    "Shutter Island": {"genres": ["thriller"], "duration": 138, "IMDB_rating": 8},
    "Parasite": {"genres": ["thriller"], "duration": 132, "IMDB_rating": 9},
    "Platform": {"genres": ["thriller"], "duration": 94, "IMDB_rating": 6},
    "Titanic": {"genres": ["romance"], "duration": 195, "IMDB_rating": 8},
    "Blended": {"genres": ["romance"], "duration": 117, "IMDB_rating": 6},
    "The Proposal": {"genres": ["romance"], "duration": 108, "IMDB_rating": 7},
    "Oppenheimer": {"genres": ["biography"], "duration": 130, "IMDB_rating": 9},
    "Hamilton": {"genres": ["biography"], "duration": 147, "IMDB_rating": 9},
    "Everest": {"genres": ["biography"], "duration": 196, "IMDB_rating": 7},
    "Avatar": {"genres": ["action", "adventure", "fantasy"], "duration": 162, "IMDB_rating": 8},
    "The Silence of the Lambs": {"genres": ["crime", "drama", "thriller"], "duration": 118, "IMDB_rating": 9},
    "Goodfellas": {"genres": ["biography", "crime", "drama"], "duration": 146, "IMDB_rating": 8},
    "Interstellar": {"genres": ["adventure", "drama", "sci-fi"], "duration": 169, "IMDB_rating": 9},
    "The Green Mile": {"genres": ["crime", "drama", "fantasy"], "duration": 189, "IMDB_rating": 9},
    "Gladiator": {"genres": ["action", "adventure", "drama"], "duration": 155, "IMDB_rating": 8},
    "The Departed": {"genres": ["crime", "drama", "thriller"], "duration": 151, "IMDB_rating": 9},
    "The Prestige": {"genres": ["drama", "mystery", "sci-fi"], "duration": 130, "IMDB_rating": 8},
    "The Lion King": {"genres": ["animation", "adventure", "drama"], "duration": 88, "IMDB_rating": 7},
    "Forrest Gump": {"genres": ["comedy", "drama", "romance"], "duration": 142, "IMDB_rating": 8},
    "The Pursuit of Happyness": {"genres": ["biography", "drama"], "duration": 117, "IMDB_rating": 7},
    "The Social Network": {"genres": ["biography", "drama"], "duration": 120, "IMDB_rating": 8},
    "Gone Girl": {"genres": ["crime", "drama", "mystery"], "duration": 149, "IMDB_rating": 8},
    "Catch Me If You Can": {"genres": ["biography", "crime", "drama"], "duration": 141, "IMDB_rating": 8},
    "The Revenant": {"genres": ["action", "adventure", "biography"], "duration": 156, "IMDB_rating": 9},
    "The Intouchables": {"genres": ["biography", "comedy", "drama"], "duration": 112, "IMDB_rating": 9},
    "Inglourious Basterds": {"genres": ["adventure", "drama", "war"], "duration": 153, "IMDB_rating": 9},
    "The Grand Budapest Hotel": {"genres": ["adventure", "comedy", "crime"], "duration": 99, "IMDB_rating": 8},
    "The Wolf of Wall Street": {"genres": ["biography", "crime", "drama"], "duration": 180, "IMDB_rating": 9},
    "La La Land": {"genres": ["comedy", "drama", "music"], "duration": 128, "IMDB_rating": 8},
    "The Avengers": {"genres": ["action", "adventure", "sci-fi"], "duration": 143, "IMDB_rating": 8},
    "Deadpool": {"genres": ["action", "adventure", "comedy"], "duration": 108, "IMDB_rating": 7}
}
